let gamesequence = []; // Stores the sequence generated by the game  
let usersequence = []; // Stores the sequence entered by the user  

let buttons = ["yellow", "red", "purple", "green"]; // List of button colors  
let started = false; // Keeps track if the game has started or not  
let level = 0; // Keeps track of the current level  

let h2 = document.querySelector("h2"); // Selects the <h2> heading to update game messages  

document.addEventListener("keypress", function()  
{  
    if (!started) // If the game has not started yet  
    {  
        console.log("game is started"); // Shows a message in the console  
        started = true; // Changes started to true so the game doesn't restart again  
        levelup(); // Calls the function to start the game  
    }  
});  

function buttonflash(button)  
{  
    if (!button) return; // If button is missing, stop the function to prevent errors  

    button.classList.add("flash"); // Adds the "flash" effect to the button  
    //setTimeout(function, delay);

    setTimeout(function()  
    {  
        button.classList.remove("flash"); // Removes the "flash" effect after 0.2 seconds  
    }, 200);  
}  

function levelup()  
{  
    usersequence = []; // Clears the user's sequence for the new level  
    level++; // Increases the level by 1  
    h2.innerText = `Level ${level}`; // Updates the <h2> to show the current level  

    let randomindex = Math.floor(Math.random() * buttons.length); // Picks a random number from 0 to 3  
    let randomcolor = buttons[randomindex]; // Selects a color from the buttons array  

    let randombutton = document.querySelector(`.${randomcolor}`); // Finds the button with the chosen color  
    console.log(randombutton); // Logs the selected button  
    console.log(randomcolor); // Logs the color name  
    console.log(randomindex); // Logs the index number  

    gamesequence.push(randomcolor); // Adds the selected color to the game sequence  
    console.log(gamesequence); // Logs the full game sequence  

    buttonflash(randombutton); // Makes the chosen button flash  
}

function checkans(index)  
{  
    index = usersequence.length - 1; // Fixes the index to check the latest input  

    if (usersequence[index] === gamesequence[index]) // Checks if the latest user input matches the game sequence  
    {  
        if(usersequence.length == gamesequence.length) // If the user completed the full sequence correctly  
        {
            setTimeout(levelup, 1000); // Waits 1 second, then moves to the next level  
        }
        console.log("same value"); // Logs that the values match  
    }  
    else  
    {  
        h2.innerHTML = `Game over! Your score was <b>${level}</b> <br> Press any key to start.`; // Shows game over message  
        document.querySelector("body").style.backgroundColor = "red"; // Changes background to red  

        setTimeout(function()  
        {  
            document.querySelector("body").style.backgroundColor = "white"; // Changes background back to white after 0.2 seconds  
        }, 200);  

        reset(); // Calls function to reset the game  
    }  
}  

function userflash(button)  
{  
    if (!button) return; // If no button is clicked, stop the function  

    button.classList.add("userflash"); // Adds a class to make the button flash when clicked  
    setTimeout(function()  
    {  
        button.classList.remove("userflash"); // Removes the class after 0.2 seconds  
    }, 200);  
}

function buttonpress()  
{  
    console.log("button was pressed"); // Logs a message when a button is clicked  
    let btn = this; // Gets the button that was clicked  
    console.log(this); // Logs the clicked button  
    userflash(btn); // Calls the function to make the button flash  

    usercolor = btn.getAttribute("id"); // Gets the color of the clicked button  
    usersequence.push(usercolor); // Adds the clicked color to the user's sequence  
    console.log(usercolor); // Logs the clicked color  

    checkans(usersequence.length - 1); // Calls function to check if the input is correct  
}

let allbuttons = document.querySelectorAll(".btn"); // Selects all buttons with the class "btn"  

for (let btn of allbuttons) // Loops through each button  
{  
    btn.addEventListener("click", buttonpress); // Adds a click event to each button  
}

function reset()  
{  
    started = false; // Sets started to false so the game can restart  
    gamesequence = []; // Clears the game sequence  
    usersequence = []; // Clears the user sequence  
    level = 0; // Resets the level back to 0  
}


//usersequence[index] === gamesequence[index]

//This ensures that the latest input exactly matches the corresponding value in gamesequence.
//if (usersequence.length === gamesequence.length)
//This ensures the player has completed the full sequence before leveling up.